chore: add clang-tidy
cose-wg/COSE-C pull request #84
Opened 2020-04-20 06:58 UTC by gocarlos

2020-04-20 16:29 UTC, gocarlos commented
@jimsch please review

2020-04-20 16:30 UTC, gocarlos commented
you will see the CI in the `actions` tab here in github after merging this, currently only in my fork: https://github.com/gocarlos/COSE-C/actions/runs/82682570

2020-04-20 20:00 UTC, jimsch requested changes
When I look at the pointer above, I am not seeing the tests being run.   Is that because they aren't run in the artifacts but are run elsewhere or because they are just not being run?

2020-04-20 20:00 UTC, jimsch commented on .github/workflows/main.yml
> +            "-DCOSE_C_INCLUDE_ENCRYPT=OFF -DCOSE_C_INCLUDE_encrypt0=ON -DCOSE_C_INCLUDE_MAC0=OFF -DCOSE_C_INCLUDE_MAC=OFF -DCOSE_C_INCLUDE_SIGN=OFF -DCOSE_C_INCLUDE_SIGN1=OFF",
COSE_C_INCLUDE_encrypt0 should be capitalized.

2020-04-20 20:00 UTC, jimsch commented on CMakeLists.txt
> +    message(STATUS "clang-tidy found: ${CLANG_TIDY_EXE}")
This message seems redundant as you are dumping out in the epilog list of objects.  No action required.

2020-04-21 07:24 UTC, gocarlos commented
To keep MRs as small as possible: this one does not run tests, we run them already with travis and appveyer....

Here we only to static analysis with clan-tidy...

We can port tests to here in the future..

2020-04-21 17:29 UTC, merged